#!/bin/bash
# Quick command reference for telegram bot deployment

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║              📋 COMANDO DE REFERENCIA - TELEGRAM BOT                       ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "📍 Ubicación del proyecto:"
echo "   /home/oficina_ia/oficina_abuelos"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "1️⃣  CONFIGURAR TOKEN (solo primera vez):"
echo ""
echo "   cd /home/oficina_ia/oficina_abuelos"
echo "   sed -i 's/your-telegram-bot-token-here/TU_TOKEN_DEL_BOTFATHER/' .env"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "2️⃣  EJECUTAR EL BOT:"
echo ""
echo "   Opción A (Script automático con verificaciones):"
echo "   cd /home/oficina_ia/oficina_abuelos && bash deploy_telegram.sh"
echo ""
echo "   Opción B (Directo):"
echo "   cd /home/oficina_ia/oficina_abuelos && python3 scripts/telegram_bot.py"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "3️⃣  MONITOREO:"
echo ""
echo "   Ver logs en tiempo real:"
echo "   tail -f /home/oficina_ia/oficina_abuelos/logs/telegram_bot.log"
echo ""
echo "   Ver logs de conversaciones:"
echo "   tail -f /home/oficina_ia/oficina_abuelos/logs/oficina.log"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "4️⃣  DETENER EL BOT:"
echo ""
echo "   Presiona Ctrl+C en la terminal donde está corriendo"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "📚 DOCUMENTACIÓN:"
echo ""
echo "   Guía completa:  TELEGRAM_BOT_README.md"
echo "   Setup rápido:   SETUP_TELEGRAM_RAPIDO.txt"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
